### ISSUE TITLE
Can't get this action to work in my workflow

### ISSUE THREAD

**Issue by pieterbreed** [nnichols/clojure-dependency-update-action#16]
# Bug Report

## Describe the Bug

When I specify the `branch` action parameter, I get an error `error: pathspec 'main' did not match any file(s) known to git`

### Steps to Reproduce

With this workflow config:

```
name: update-clj-cljs-dependencies-and-make-PR
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check clj/s dependencies and create merge-request
        uses: nnichols/clojure-dependency-update-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          batch: "true"
          branch: "main"
```

I get this output in actions:

```
Run nnichols/clojure-dependency-update-action@v4
18
/usr/bin/docker run --name c42e57923e2a0451aab170b1b6061e399_88b4b7 --label 49859c --workdir /github/workspace --rm -e "INPUT_GITHUB-TOKEN" -e "INPUT_BATCH" -e "INPUT_BRANCH" -e "INPUT_GIT-EMAIL" -e "INPUT_GIT-USERNAME" -e "INPUT_EXCLUDES" -e "INPUT_DIRECTORIES" -e "INPUT_SKIPS" -e "TOKEN" -e "EMAIL" -e "NAME" -e "BRANCH" -e "EXCLUDE" -e "DIRECTORY" -e "SKIP" -e "BATCH" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nette/nette":"/github/workspace" 49859c:42e57923e2a0451aab170b1b6061e399
19
error: pathspec 'main' did not match any file(s) known to git
20
Downloading: antq/antq/maven-metadata.xml from clojars
21
Downloading: antq/antq/maven-metadata.xml from datomic-cloud
22
Cloning: https://github.com/simongray/datalinguist
...
Your branch is up to date with 'origin/pieter/net-679-update-dependencies-in-depsedn'.
unknown argument "main"; please quote all values that have spaces

Usage:  gh pr create [flags]

Flags:
  -a, --assignee login    Assign people by their login
  -B, --base branch       The branch into which you want your code merged
  -b, --body string       Body for the pull request
  -d, --draft             Mark pull request as a draft
  -f, --fill              Do not prompt for title/body and just use commit info
  -H, --head branch       The branch that contains commits for your pull request (default: current branch)
  -l, --label name        Add labels by name
  -m, --milestone name    Add the pull request to a milestone by name
  -p, --project name      Add the pull request to projects by name
      --recover string    Recover input from a failed run of create
  -r, --reviewer handle   Request reviews from people or teams by their handle
  -t, --title string      Title for the pull request
  -w, --web               Open the web browser to create a pull request
```
