### ISSUE TITLE
Update process is failing

### ISSUE THREAD

**Issue by fdabrao** [nnichols/clojure-dependency-update-action#21]
# Bug Report

## Describe the Bug

Two weeks ago it start to runing this error:
![image](https://github.com/nnichols/clojure-dependency-update-action/assets/17049832/d63b0fde-002e-4c10-9554-bf591e32b38d)

### User Information
```yml
name: Batch Dependency Update

on:
  workflow_dispatch:

  schedule:
    - cron: "50 1 * * 1" # Mondays at 1:50 AM

jobs:
  update-deps:
    name: Update dependencies

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2.3.4

    - name: Check deps
      uses:  nnichols/clojure-dependency-update-action@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        batch: "true"
        branch: "development"
        skips: "github-action"
```
